export class Productos{
    public IdProducto: number;
    public IdTipoMedida: number;
    public TipoMedidaDescripcion: string;
    public IdTipoCategoria: number;
    public CategoriaDescripcion: string;
    public IdTipoProducto: number;
    public TipoProductoDescripcion: string;
    public Codigo: string;
    public Nombre: string;
    public Marca: string;
    public PrecioCosto: number;
    public Tamaño: number;
    public CantMaxima: number;
    public CantMinima: number;
    public IdUsuarioCarga: number;
    public FechaAlta: number;
    public FechaBaja: number;
}