-- MySQL Script generated by MySQL Workbench
-- Wed Apr 24 15:41:03 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema cleanbd
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `cleanbd` ;

-- -----------------------------------------------------
-- Schema cleanbd
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `cleanbd` DEFAULT CHARACTER SET utf8 ;
USE `cleanbd` ;

-- -----------------------------------------------------
-- Table `cleanbd`.`TipoPersona`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cleanbd`.`TipoPersona` (
  `IdTipoPersona` INT NOT NULL AUTO_INCREMENT,
  `Descripcion` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`IdTipoPersona`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cleanbd`.`TipoDocumentacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cleanbd`.`TipoDocumentacion` (
  `IdTipoDocumentacion` INT NOT NULL AUTO_INCREMENT,
  `Descripcion` VARCHAR(45) NULL,
  PRIMARY KEY (`IdTipoDocumentacion`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cleanbd`.`TipoDomicilio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cleanbd`.`TipoDomicilio` (
  `IdTipoDomicilio` INT NOT NULL,
  `Descripcion` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`IdTipoDomicilio`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cleanbd`.`Domicilio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cleanbd`.`Domicilio` (
  `IdDomicilio` INT NOT NULL,
  `IdTipoDomicilio` INT NOT NULL,
  `Calle` VARCHAR(45) NOT NULL,
  `Nro` VARCHAR(45) NULL,
  `Piso` VARCHAR(45) NULL,
  PRIMARY KEY (`IdDomicilio`),
  INDEX `fk_Domicilio_TipoDomicilio1_idx` (`IdTipoDomicilio` ASC),
  CONSTRAINT `fk_Domicilio_TipoDomicilio1`
    FOREIGN KEY (`IdTipoDomicilio`)
    REFERENCES `cleanbd`.`TipoDomicilio` (`IdTipoDomicilio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cleanbd`.`Provincia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cleanbd`.`Provincia` (
  `IdProvincia` INT NOT NULL,
  `Provincia` VARCHAR(45) NOT NULL,
  `Localidad` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`IdProvincia`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cleanbd`.`TipoPersonaSistema`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cleanbd`.`TipoPersonaSistema` (
  `IdTipoPersonaSistema` INT NOT NULL AUTO_INCREMENT,
  `Descripcion` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`IdTipoPersonaSistema`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cleanbd`.`Persona`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cleanbd`.`Persona` (
  `IdPersona` INT NOT NULL AUTO_INCREMENT,
  `IdTipoPersonaSistema` INT NOT NULL,
  `IdTipoDocumentacion` INT NOT NULL,
  `IdTipoPersona` INT NOT NULL,
  `IdDomicilio` INT NOT NULL,
  `IdProvincia` INT NOT NULL,
  `Nombre` VARCHAR(45) NOT NULL,
  `Apellido` VARCHAR(45) NOT NULL,
  `Mail` VARCHAR(45) NOT NULL,
  `RazonSocial` VARCHAR(45) NOT NULL,
  `FechaNacimiento` DATE NULL,
  `Telefono` VARCHAR(45) NULL,
  `FechaAlta` DATETIME NOT NULL,
  `FechaBaja` DATETIME NULL,
  PRIMARY KEY (`IdPersona`),
  INDEX `fk_Persona_TipoPersona1_idx` (`IdTipoPersona` ASC) ,
  INDEX `fk_Persona_TipoDocumentacion1_idx` (`IdTipoDocumentacion` ASC) ,
  INDEX `fk_Persona_Domicilio1_idx` (`IdDomicilio` ASC) ,
  INDEX `fk_Persona_Provincia1_idx` (`IdProvincia` ASC) ,
  INDEX `fk_Persona_TipoPersonaSistema1_idx` (`IdTipoPersonaSistema` ASC) ,
  CONSTRAINT `fk_Persona_TipoPersona1`
    FOREIGN KEY (`IdTipoPersona`)
    REFERENCES `cleanbd`.`TipoPersona` (`IdTipoPersona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Persona_TipoDocumentacion1`
    FOREIGN KEY (`IdTipoDocumentacion`)
    REFERENCES `cleanbd`.`TipoDocumentacion` (`IdTipoDocumentacion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Persona_Domicilio1`
    FOREIGN KEY (`IdDomicilio`)
    REFERENCES `cleanbd`.`Domicilio` (`IdDomicilio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Persona_Provincia1`
    FOREIGN KEY (`IdProvincia`)
    REFERENCES `cleanbd`.`Provincia` (`IdProvincia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Persona_TipoPersonaSistema1`
    FOREIGN KEY (`IdTipoPersonaSistema`)
    REFERENCES `cleanbd`.`TipoPersonaSistema` (`IdTipoPersonaSistema`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cleanbd`.`Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cleanbd`.`Usuario` (
  `IdUsuario` INT NOT NULL AUTO_INCREMENT,
  `IdPersona` INT NOT NULL,
  `Usuario` VARCHAR(45) NOT NULL,
  `Clave` VARCHAR(255) NOT NULL,
  `IdUsuarioCarga` VARCHAR(45) NOT NULL,
  `FechaAlta` DATETIME NOT NULL,
  `FechaBaja` DATETIME NULL,
  PRIMARY KEY (`IdUsuario`),
  INDEX `fk_Usuario_Persona1_idx` (`IdPersona` ASC) ,
  CONSTRAINT `fk_Usuario_Persona1`
    FOREIGN KEY (`IdPersona`)
    REFERENCES `cleanbd`.`Persona` (`IdPersona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cleanbd`.`TipoRol`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cleanbd`.`TipoRol` (
  `IdTipoRol` INT NOT NULL AUTO_INCREMENT,
  `Descripcion` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`IdTipoRol`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cleanbd`.`TipoPermiso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cleanbd`.`TipoPermiso` (
  `IdTipoPermiso` INT NOT NULL,
  `Detalle` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`IdTipoPermiso`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cleanbd`.`TipoModulo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cleanbd`.`TipoModulo` (
  `IdTipoModulo` INT NOT NULL,
  `IdPadre` VARCHAR(10) NOT NULL,
  `Orden` VARCHAR(45) NOT NULL,
  `Detalle` VARCHAR(45) NOT NULL,
  `PathRout` VARCHAR(45) NOT NULL,
  `TipoMenu` INT NOT NULL,
  `TipoIcono` VARCHAR(45) NOT NULL,
  `Icono` VARCHAR(255) NOT NULL,
  `FechaAlta` DATETIME NOT NULL,
  `FechaBaja` DATETIME NULL,
  PRIMARY KEY (`IdTipoModulo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cleanbd`.`RolModulo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cleanbd`.`RolModulo` (
  `IdRolModulo` INT NOT NULL,
  `IdRolTipo` INT NOT NULL,
  `IdTipoModulo` INT NOT NULL,
  `IdTipoPermiso` INT NOT NULL,
  PRIMARY KEY (`IdRolModulo`),
  INDEX `fk_RolModulo_RolTipo1_idx` (`IdRolTipo` ASC) ,
  INDEX `fk_RolModulo_TipoModulo1_idx` (`IdTipoModulo` ASC) ,
  INDEX `fk_RolModulo_TipoPermiso1_idx` (`IdTipoPermiso` ASC) ,
  CONSTRAINT `fk_RolModulo_RolTipo1`
    FOREIGN KEY (`IdRolTipo`)
    REFERENCES `cleanbd`.`TipoRol` (`IdTipoRol`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_RolModulo_TipoModulo1`
    FOREIGN KEY (`IdTipoModulo`)
    REFERENCES `cleanbd`.`TipoModulo` (`IdTipoModulo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_RolModulo_TipoPermiso1`
    FOREIGN KEY (`IdTipoPermiso`)
    REFERENCES `cleanbd`.`TipoPermiso` (`IdTipoPermiso`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cleanbd`.`Sucursal`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cleanbd`.`Sucursal` (
  `IdSucursal` INT NOT NULL,
  `IdDomicilio` INT NOT NULL,
  `Descripcion` VARCHAR(45) NOT NULL,
  `IdUsuarioCarga` INT NOT NULL,
  `FechaAlta` DATETIME NOT NULL,
  `FechaBaja` DATETIME NULL,
  PRIMARY KEY (`IdSucursal`),
  INDEX `fk_Sucursal_Usuario1_idx` (`IdUsuarioCarga` ASC) ,
  INDEX `fk_Sucursal_Domicilio1_idx` (`IdDomicilio` ASC) ,
  CONSTRAINT `fk_Sucursal_Usuario1`
    FOREIGN KEY (`IdUsuarioCarga`)
    REFERENCES `cleanbd`.`Usuario` (`IdUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Sucursal_Domicilio1`
    FOREIGN KEY (`IdDomicilio`)
    REFERENCES `cleanbd`.`Domicilio` (`IdDomicilio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cleanbd`.`UsuarioPorSucursal`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cleanbd`.`UsuarioPorSucursal` (
  `IdUsuarioPorSucursal` INT NOT NULL AUTO_INCREMENT,
  `IdUsuario` INT NOT NULL,
  `IdSucursal` INT NOT NULL,
  `FechaUltModificacion` DATETIME NOT NULL,
  `FechaAlta` DATETIME NOT NULL,
  `FechaBaja` DATETIME NULL,
  PRIMARY KEY (`IdUsuarioPorSucursal`),
  INDEX `fk_UsuarioPorSucursal_Usuario1_idx` (`IdUsuario` ASC) ,
  INDEX `fk_UsuarioPorSucursal_Sucursal1_idx` (`IdSucursal` ASC) ,
  CONSTRAINT `fk_UsuarioPorSucursal_Usuario1`
    FOREIGN KEY (`IdUsuario`)
    REFERENCES `cleanbd`.`Usuario` (`IdUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_UsuarioPorSucursal_Sucursal1`
    FOREIGN KEY (`IdSucursal`)
    REFERENCES `cleanbd`.`Sucursal` (`IdSucursal`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cleanbd`.`TipoPermisoDetalle`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cleanbd`.`TipoPermisoDetalle` (
  `IdTipoPermisoDetalle` INT NOT NULL,
  `IdTipoPermiso` INT NOT NULL,
  `Method` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`IdTipoPermisoDetalle`),
  INDEX `fk_TipoPermisoDetalle_TipoPermiso1_idx` (`IdTipoPermiso` ASC) ,
  CONSTRAINT `fk_TipoPermisoDetalle_TipoPermiso1`
    FOREIGN KEY (`IdTipoPermiso`)
    REFERENCES `cleanbd`.`TipoPermiso` (`IdTipoPermiso`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cleanbd`.`SistemaAPIs`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cleanbd`.`SistemaAPIs` (
  `IdSistemaAPIs` INT NOT NULL,
  `Detalle` VARCHAR(45) NOT NULL,
  `Method` VARCHAR(45) NOT NULL,
  `Path` VARCHAR(45) NOT NULL,
  `IdUsuarioCarga` INT NOT NULL,
  `FechaAlta` DATETIME NOT NULL,
  `FechaBaja` DATETIME NULL,
  PRIMARY KEY (`IdSistemaAPIs`),
  INDEX `fk_SistemaAPIs_Usuario1_idx` (`IdUsuarioCarga` ASC) ,
  CONSTRAINT `fk_SistemaAPIs_Usuario1`
    FOREIGN KEY (`IdUsuarioCarga`)
    REFERENCES `cleanbd`.`Usuario` (`IdUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cleanbd`.`SistemaModuloAPIs`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cleanbd`.`SistemaModuloAPIs` (
  `IdSistemaModuloAPIs` INT NOT NULL,
  `IdTipoModulo` INT NOT NULL,
  `IdSistemasAPIs` INT NOT NULL,
  `IdUsuarioCarga` INT NOT NULL,
  `FechaAlta` DATETIME NOT NULL,
  `FechaBaja` DATETIME NULL,
  PRIMARY KEY (`IdSistemaModuloAPIs`),
  INDEX `fk_SistemaModuloAPIs_TipoModulo1_idx` (`IdTipoModulo` ASC) ,
  INDEX `fk_SistemaModuloAPIs_SistemaAPIs1_idx` (`IdSistemasAPIs` ASC) ,
  INDEX `fk_SistemaModuloAPIs_Usuario1_idx` (`IdUsuarioCarga` ASC) ,
  CONSTRAINT `fk_SistemaModuloAPIs_TipoModulo1`
    FOREIGN KEY (`IdTipoModulo`)
    REFERENCES `cleanbd`.`TipoModulo` (`IdTipoModulo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_SistemaModuloAPIs_SistemaAPIs1`
    FOREIGN KEY (`IdSistemasAPIs`)
    REFERENCES `cleanbd`.`SistemaAPIs` (`IdSistemaAPIs`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_SistemaModuloAPIs_Usuario1`
    FOREIGN KEY (`IdUsuarioCarga`)
    REFERENCES `cleanbd`.`Usuario` (`IdUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cleanbd`.`TipoProducto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cleanbd`.`TipoProducto` (
  `IdTipoProducto` INT NOT NULL,
  `Detalle` VARCHAR(45) NOT NULL,
  `FechaAlta` INT NOT NULL,
  `FechaBaja` INT NULL,
  PRIMARY KEY (`IdTipoProducto`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cleanbd`.`TipoCategoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cleanbd`.`TipoCategoria` (
  `IdTipoCategoria` INT NOT NULL AUTO_INCREMENT,
  `Descripcion` VARCHAR(255) NOT NULL,
  `FechaAlta` DATETIME NOT NULL,
  `FechaBaja` DATETIME NULL,
  PRIMARY KEY (`IdTipoCategoria`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cleanbd`.`TipoMedida`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cleanbd`.`TipoMedida` (
  `IdTipoMedida` INT NOT NULL,
  `Detalle` VARCHAR(45) NOT NULL,
  `Abreviatura` VARCHAR(45) NOT NULL,
  `FechaAlta` DATETIME NOT NULL,
  `FechaBaja` DATETIME NULL,
  PRIMARY KEY (`IdTipoMedida`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cleanbd`.`Producto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cleanbd`.`Producto` (
  `IdProducto` INT NOT NULL,
  `IdTipoMedida` INT NOT NULL,
  `IdTipoCategoria` INT NOT NULL,
  `IdTipoProducto` INT NOT NULL,
  `IdTipoEnvase` INT NOT NULL,
  `Codigo` VARCHAR(255) NOT NULL,
  `Nombre` VARCHAR(45) NOT NULL,
  `Marca` VARCHAR(45) NOT NULL,
  `PrecioCosto` DECIMAL(18,2) NOT NULL,
  `Tamaño` DECIMAL(18,2) NOT NULL,
  `TieneDesc` BIT NOT NULL,
  `MinDesc` DECIMAL(18,2) NOT NULL,
  `DescUnitario` DECIMAL(18,2) NOT NULL,
  `IdUsuarioCarga` INT NOT NULL,
  `FechaAlta` DATETIME NOT NULL,
  `FechaBaja` DATETIME NULL,
  PRIMARY KEY (`IdProducto`),
  INDEX `fk_Producto_TipoCategoria1_idx` (`IdTipoCategoria` ASC) ,
  INDEX `fk_Productos_TipoProducto1_idx` (`IdTipoProducto` ASC) ,
  INDEX `fk_Productos_TipoMedida1_idx` (`IdTipoMedida` ASC) ,
  INDEX `fk_Producto_Usuario1_idx` (`IdUsuarioCarga` ASC) ,
  CONSTRAINT `fk_Producto_TipoCategoria1`
    FOREIGN KEY (`IdTipoCategoria`)
    REFERENCES `cleanbd`.`TipoCategoria` (`IdTipoCategoria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Productos_TipoProducto1`
    FOREIGN KEY (`IdTipoProducto`)
    REFERENCES `cleanbd`.`TipoProducto` (`IdTipoProducto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Productos_TipoMedida1`
    FOREIGN KEY (`IdTipoMedida`)
    REFERENCES `cleanbd`.`TipoMedida` (`IdTipoMedida`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Producto_Usuario1`
    FOREIGN KEY (`IdUsuarioCarga`)
    REFERENCES `cleanbd`.`Usuario` (`IdUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cleanbd`.`StockSucursal`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cleanbd`.`StockSucursal` (
  `IdStockSucursal` INT NOT NULL AUTO_INCREMENT,
  `IdProducto` INT NOT NULL,
  `IdSucursal` INT NOT NULL,
  `Cantidad` DECIMAL(18,2) NOT NULL,
  `IdUsuarioUltMod` INT NOT NULL,
  `FechaAlta` INT NOT NULL,
  `FechaUltMod` INT NOT NULL,
  `FechaBaja` INT NULL,
  PRIMARY KEY (`IdStockSucursal`),
  INDEX `fk_StockSucursales_Producto1_idx` (`IdProducto` ASC) ,
  INDEX `fk_StockSucursales_Sucursal1_idx` (`IdSucursal` ASC) ,
  INDEX `fk_StockSucursales_Usuario1_idx` (`IdUsuarioUltMod` ASC) ,
  CONSTRAINT `fk_StockSucursales_Producto1`
    FOREIGN KEY (`IdProducto`)
    REFERENCES `cleanbd`.`Producto` (`IdProducto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_StockSucursales_Sucursal1`
    FOREIGN KEY (`IdSucursal`)
    REFERENCES `cleanbd`.`Sucursal` (`IdSucursal`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_StockSucursales_Usuario1`
    FOREIGN KEY (`IdUsuarioUltMod`)
    REFERENCES `cleanbd`.`Usuario` (`IdUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cleanbd`.`TipoFactura`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cleanbd`.`TipoFactura` (
  `IdTipoFactura` INT NOT NULL AUTO_INCREMENT,
  `Descripcion` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`IdTipoFactura`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cleanbd`.`TipoDestinatarioFactura`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cleanbd`.`TipoDestinatarioFactura` (
  `IdTipoDestinatarioFactura` INT NOT NULL AUTO_INCREMENT,
  `Descripcion` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`IdTipoDestinatarioFactura`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cleanbd`.`TipoFormaDePago`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cleanbd`.`TipoFormaDePago` (
  `IdTipoFormaDePago` INT NOT NULL AUTO_INCREMENT,
  `Descripcion` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`IdTipoFormaDePago`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cleanbd`.`Factura`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cleanbd`.`Factura` (
  `IdFactura` INT NOT NULL AUTO_INCREMENT,
  `IdTipoDestinatarioFactura` INT NOT NULL,
  `IdTipoFactura` INT NOT NULL,
  `IdFormaDePago` INT NOT NULL,
  `FechaEmision` DATETIME NOT NULL,
  PRIMARY KEY (`IdFactura`),
  INDEX `fk_Facturas_TipoFactura1_idx` (`IdTipoFactura` ASC) ,
  INDEX `fk_Facturas_TipoDestinatarioFactura1_idx` (`IdTipoDestinatarioFactura` ASC) ,
  INDEX `fk_Facturas_FormaDePago1_idx` (`IdFormaDePago` ASC) ,
  CONSTRAINT `fk_Facturas_TipoFactura1`
    FOREIGN KEY (`IdTipoFactura`)
    REFERENCES `cleanbd`.`TipoFactura` (`IdTipoFactura`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Facturas_TipoDestinatarioFactura1`
    FOREIGN KEY (`IdTipoDestinatarioFactura`)
    REFERENCES `cleanbd`.`TipoDestinatarioFactura` (`IdTipoDestinatarioFactura`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Facturas_FormaDePago1`
    FOREIGN KEY (`IdFormaDePago`)
    REFERENCES `cleanbd`.`TipoFormaDePago` (`IdTipoFormaDePago`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cleanbd`.`DetalleFactura`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cleanbd`.`DetalleFactura` (
  `IdDetalleFactura` INT NOT NULL AUTO_INCREMENT,
  `IdFacturas` INT NOT NULL,
  `SubTotal` DECIMAL(18,2) NOT NULL,
  `Total` DECIMAL(18,2) NOT NULL,
  `DescVenta` DECIMAL(18,2) NOT NULL,
  `IncrementoVenta` DECIMAL(18,2) NOT NULL,
  `Pago` DECIMAL(18,2) NOT NULL,
  `Vuelto` DECIMAL(18,2) NOT NULL,
  PRIMARY KEY (`IdDetalleFactura`),
  INDEX `fk_DetalleFactura_Facturas1_idx` (`IdFacturas` ASC) ,
  CONSTRAINT `fk_DetalleFactura_Facturas1`
    FOREIGN KEY (`IdFacturas`)
    REFERENCES `cleanbd`.`Factura` (`IdFactura`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cleanbd`.`TipoImpuesto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cleanbd`.`TipoImpuesto` (
  `IdTipoImpuesto` INT NOT NULL,
  `Detalle` VARCHAR(45) NOT NULL,
  `Porcentaje` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`IdTipoImpuesto`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cleanbd`.`Venta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cleanbd`.`Venta` (
  `IdVenta` INT NOT NULL AUTO_INCREMENT,
  `IdDetalleFactura` INT NOT NULL,
  `IdTipoImpuesto` INT NOT NULL,
  `IdSucursal` INT NOT NULL,
  `Fecha` DATETIME NOT NULL,
  `NroVenta` INT NOT NULL,
  `Cantidad` DECIMAL(18,2) NOT NULL,
  `IdUsuarioCarga` INT NOT NULL,
  `FechaAlta` DATETIME NOT NULL,
  `FechaBaja` DATETIME NULL,
  PRIMARY KEY (`IdVenta`),
  INDEX `fk_Ventas_DetalleFactura1_idx` (`IdDetalleFactura` ASC) ,
  INDEX `fk_Ventas_Sucursal1_idx` (`IdSucursal` ASC) ,
  INDEX `fk_Ventas_TipoImpuestos1_idx` (`IdTipoImpuesto` ASC) ,
  INDEX `fk_Ventas_Usuario1_idx` (`IdUsuarioCarga` ASC) ,
  CONSTRAINT `fk_Ventas_DetalleFactura1`
    FOREIGN KEY (`IdDetalleFactura`)
    REFERENCES `cleanbd`.`DetalleFactura` (`IdDetalleFactura`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Ventas_Sucursal1`
    FOREIGN KEY (`IdSucursal`)
    REFERENCES `cleanbd`.`Sucursal` (`IdSucursal`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Ventas_TipoImpuestos1`
    FOREIGN KEY (`IdTipoImpuesto`)
    REFERENCES `cleanbd`.`TipoImpuesto` (`IdTipoImpuesto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Ventas_Usuario1`
    FOREIGN KEY (`IdUsuarioCarga`)
    REFERENCES `cleanbd`.`Usuario` (`IdUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cleanbd`.`PedidosSucursal`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cleanbd`.`PedidosSucursal` (
  `IdPedidosSucursal` INT NOT NULL AUTO_INCREMENT,
  `IdUsuario` INT NOT NULL,
  `IdSucursal` INT NOT NULL,
  `Fecha` DATETIME NOT NULL,
  `CantBulto` INT NOT NULL,
  `Estado` VARCHAR(55) NOT NULL,
  `FechaEnvio` DATETIME NOT NULL,
  `FechaEntrega` DATETIME NOT NULL,
  PRIMARY KEY (`IdPedidosSucursal`),
  INDEX `fk_PedidosSucursales_Usuario1_idx` (`IdUsuario` ASC) ,
  INDEX `fk_PedidosSucursales_Sucursal1_idx` (`IdSucursal` ASC) ,
  CONSTRAINT `fk_PedidosSucursales_Usuario1`
    FOREIGN KEY (`IdUsuario`)
    REFERENCES `cleanbd`.`Usuario` (`IdUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_PedidosSucursales_Sucursal1`
    FOREIGN KEY (`IdSucursal`)
    REFERENCES `cleanbd`.`Sucursal` (`IdSucursal`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cleanbd`.`ProductoPorPedido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cleanbd`.`ProductoPorPedido` (
  `IdProductoPorPedido` INT NOT NULL,
  `IdPedidoSucursal` INT NOT NULL,
  `IdProductos` INT NOT NULL,
  PRIMARY KEY (`IdProductoPorPedido`),
  INDEX `fk_ProductosPorPedido_PedidosSucursales1_idx` (`IdPedidoSucursal` ASC) ,
  INDEX `fk_ProductosPorPedido_Productos1_idx` (`IdProductos` ASC) ,
  CONSTRAINT `fk_ProductosPorPedido_PedidosSucursales1`
    FOREIGN KEY (`IdPedidoSucursal`)
    REFERENCES `cleanbd`.`PedidosSucursal` (`IdPedidosSucursal`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ProductosPorPedido_Productos1`
    FOREIGN KEY (`IdProductos`)
    REFERENCES `cleanbd`.`Producto` (`IdProducto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cleanbd`.`Auditoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cleanbd`.`Auditoria` (
  `IdAuditoria` INT NOT NULL,
  `IdUsuario` INT NOT NULL,
  `Fecha` DATETIME NOT NULL,
  `Tabla` VARCHAR(45) NOT NULL,
  `Campo` VARCHAR(45) NOT NULL,
  `Identificador` INT NOT NULL,
  `ValorAnterior` VARCHAR(45) NOT NULL,
  `ValorActual` VARCHAR(45) NOT NULL,
  `Tipo` VARCHAR(45) NOT NULL,
  `Pendiente` BIT NOT NULL,
  PRIMARY KEY (`IdAuditoria`),
  INDEX `fk_Auditoria_Usuario1_idx` (`IdUsuario` ASC) ,
  CONSTRAINT `fk_Auditoria_Usuario1`
    FOREIGN KEY (`IdUsuario`)
    REFERENCES `cleanbd`.`Usuario` (`IdUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cleanbd`.`VentaDetalle`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cleanbd`.`VentaDetalle` (
  `IdVentaDetalle` INT NOT NULL,
  `IdVenta` INT NOT NULL,
  `IdProductos` INT NOT NULL,
  `Cantidad` DECIMAL(18,2) NULL,
  PRIMARY KEY (`IdVentaDetalle`),
  INDEX `fk_VentaDetalle_Ventas1_idx` (`IdVenta` ASC) ,
  INDEX `fk_VentaDetalle_Productos1_idx` (`IdProductos` ASC) ,
  CONSTRAINT `fk_VentaDetalle_Ventas1`
    FOREIGN KEY (`IdVenta`)
    REFERENCES `cleanbd`.`Venta` (`IdVenta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_VentaDetalle_Productos1`
    FOREIGN KEY (`IdProductos`)
    REFERENCES `cleanbd`.`Producto` (`IdProducto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cleanbd`.`GastosProtocolares`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cleanbd`.`GastosProtocolares` (
  `IdGastosProtocolares` INT NOT NULL AUTO_INCREMENT,
  `IdUsuarioCarga` INT NOT NULL,
  `IdSucursal` INT NOT NULL,
  `Descripcion` VARCHAR(45) NOT NULL,
  `Monto` DECIMAL(18,2) NOT NULL,
  PRIMARY KEY (`IdGastosProtocolares`),
  INDEX `fk_GastosProtocolares_Usuario1_idx` (`IdUsuarioCarga` ASC) ,
  INDEX `fk_GastosProtocolares_Sucursal1_idx` (`IdSucursal` ASC) ,
  CONSTRAINT `fk_GastosProtocolares_Usuario1`
    FOREIGN KEY (`IdUsuarioCarga`)
    REFERENCES `cleanbd`.`Usuario` (`IdUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_GastosProtocolares_Sucursal1`
    FOREIGN KEY (`IdSucursal`)
    REFERENCES `cleanbd`.`Sucursal` (`IdSucursal`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
